[workspace]
# Stavio sam crate-ove u `crates/` direktorijum posto cesto workspace ima vise od samo crate-ova,
# pa je zgodno imati ih sve na jednom mestu.
members = [
    # Ovo je binary koji je do sad bio ceo ovaj repo
    "crates/generator",
    # Ovo sam napravio kao primer i tu bi isao onaj drugi repo (ne moras da trosis vreme na to, dajem samo primer)
    "crates/node",
]

# Ovako mozes da definises `package` field za ceo workspace, posle u 
# svakom pojedinacnom crate-u radis nesto kao:
#
# [package]
# version.workspace = true
# edition.workspace = true
[workspace.package]
version = "0.1.0"
edition = "2024"

# Ista prica kao za `package` field, nekad zelis da koristis isti dependency u vise crate-ova, i ne zelis svuda da manage-ujes verzije pojedinacno.
# Ovako mozes da definises neke dependency-e na workspace nivou i onda u crate-u gde ti treba kazes nesto kao:
#
# [dependencies]
# sha2 = { workspace = true, features = ["some_feat"] }
[workspace.dependencies]
axum = { version = "0.8.3", features = ["__private", "ws", "macros"] }
axum-server = "0.7.2"
futures-util = "0.3.31"
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.140"
sha2 = "0.10.8"
sha256 = "1.6.0"
tokio = { version = "1.44.2", features = ["full"] }
tokio-tungstenite = "0.26.2"
tracing = "0.1.41"
tracing-subscriber = { version = "0.3.19", features = ["env-filter"] }
url = "2.5.4"
uuid = "1.16.0"
ws = "0.9.2"
